id: P614D6E53
initial_creation_type: input
source_metadata:
  title: Amitāyus Series
  language: de
  description: 'Texts related to Amitāyus (tshe dpag med), the Buddha of Boundless
    Life:'
  volume:
    01f98f0afe5c46f3a9bb5c67199eb815:
      title: 'The Bestowal of Supreme Immortality: A Prayer to the Lineage of Mitrayogin’s
        White and Red Amitāyus'
      parent: Lineage Prayers
    2dd9e30e091a46f1beb87e6edd80cda3:
      title: A Prayer to Amitāyus
      parent: Prayers
    d02a9a68a6c74979bd4bc2f2bbc5d786:
      title: A Daily Long-Life Practice of Amitāyus
      parent: Sādhanas
    2c6f2424b7fd4be682e178ffe5566fc0:
      title: 'The Sublime Path to Immortality: The Quintessence of Profoundly Secret
        Pith Instructions on Attaining Vajra Longevity'
      parent: Sādhanas
    a512ba38829e42e097720b069095c475:
      title: 'Words of Advice on Accomplishing Immortality: An Extremely Concise Daily
        Practice Uniting the Short Lineages of Amitāyus and Hayagrīva'
      parent: Sādhanas
    06c913e77b1a4abd8dc48561392ad31d:
      title: Extemporary Practice of Longevity for Oneself or Others
      parent: Sādhanas
    f272517108c34ff6a48d7b8c6295b7d3:
      title: The Dhāraṇī of Amitāyus
      parent: Sūtra
    dbea1cb6ed9e4537952f84c756d84528:
      title: The Sūtra of Boundless Life and Wisdom
      parent: Sūtra
    e8b3f535693343f4b1a9208d90146de0:
      title: How to Recite the Dhāraṇīsūtra of Amitāyus
      parent: Sūtra
created_at: '2022-03-01T02:43:20.956752'
last_modified_at: '2022-03-01T02:43:20.956755'
